### ISSUE TITLE
Double chests and Simple Key Copy

### ISSUE THREAD

**Issue by usser1976** [Mohagames205/LockMyStuff#3]
1. 
If you have a double chest locked, then only half is locked.  The other half everyone can open or break (the half content drops)

2.
If you have a chest locked (example name "test"), anyone can see the name of the key "test".  Everyone can then create their own second chest with the name "test" and open the foreign Chest with his key.

I hope you understand what I mean 😉 and sorry ... I test very carefully 😂

Greetings from Germany

**Comment by Mohagames205** [comment]
1.
Hi, thank you for reminding me about that. I will work on this as soon as possible! 

2.
You can remove the makekey permission from users so they can't make a key. But I'll change that to a command so you only can see the door name with a command. Thank you for the suggestion!

**Comment by usser1976** [comment]
I still have a suggestion 😉 maybe you could specify how many chest a player can lock 🤔

**Comment by Mohagames205** [comment]
I will try to add this soon, nice idea!

**Comment by Mohagames205** [comment]
Hi, please create a new issue for the chest issue.
