### ISSUE TITLE
Permission nodes?

### ISSUE THREAD

**Issue by ghost** [Mohagames205/LockMyStuff#5]
Hi!

Great plugin! I was wondering if you could add support for permission nodes?

Best regards,
Kim

**Comment by Mohagames205** [comment]
Hi, you can take a look at the current permissions the plugin has https://github.com/Mohagames205/LockMyStuff/blob/master/README.md#permissions

If you have any suggestions for more permissions, you can comment on this issue

**Comment by ghost** [comment]
Awesome! Thank you 😁

Best regards,
Kim

fre. 4. okt. 2019, 21:40 skrev Mohamed <notifications@github.com>:

**Comment by Mohagames205** [comment]
Have a nice day :) If you encounter any issues feel free to open an issue on the Issue Tracker

**Comment by ghost** [comment]
Will do! Thank you, you too 😊

fre. 4. okt. 2019, 21:51 skrev Mohamed <notifications@github.com>:
